HerosSimpleWebSite/Pages/Heroes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Heros.Database;

namespace Heros.Pages.Heroes
{
    public class CreateModel : PageModel
    {
        private readonly Heros.Database.HeroDbContext _context;

        public CreateModel(Heros.Database.HeroDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Hero Hero { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Heroes.Add(Hero);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

HerosSimpleWebSite/Pages/Heroes/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Heros.Database;

namespace Heros.Pages.Heroes
{
    public class DeleteModel : PageModel
    {
        private readonly Heros.Database.HeroDbContext _context;

        public DeleteModel(Heros.Database.HeroDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Hero Hero { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hero = await _context.Heroes.FirstOrDefaultAsync(m => m.Id == id);

            if (hero == null)
            {
                return NotFound();
            }
            else
            {
                Hero = hero;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hero = await _context.Heroes.FindAsync(id);
            if (hero != null)
            {
                Hero = hero;
                _context.Heroes.Remove(Hero);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

HerosSimpleWebSite/Pages/Heroes/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Heros.Database;

namespace Heros.Pages.Heroes
{
    public class DetailsModel : PageModel
    {
        private readonly Heros.Database.HeroDbContext _context;

        public DetailsModel(Heros.Database.HeroDbContext context)
        {
            _context = context;
        }

        public Hero Hero { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hero = await _context.Heroes.FirstOrDefaultAsync(m => m.Id == id);
            if (hero == null)
            {
                return NotFound();
            }
            else
            {
                Hero = hero;
            }
            return Page();
        }
    }
}

HerosSimpleWebSite/Pages/Heroes/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Heros.Database;

namespace Heros.Pages.Heroes
{
    public class EditModel : PageModel
    {
        private readonly Heros.Database.HeroDbContext _context;

        public EditModel(Heros.Database.HeroDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Hero Hero { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hero =  await _context.Heroes.FirstOrDefaultAsync(m => m.Id == id);
            if (hero == null)
            {
                return NotFound();
            }
            Hero = hero;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Hero).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!HeroExists(Hero.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool HeroExists(int id)
        {
            return _context.Heroes.Any(e => e.Id == id);
        }
    }
}

HerosSimpleWebSite/Pages/Heroes/Index.cshtml.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Heros.Database;
using System.Globalization;
using CsvHelper;

namespace Heros.Pages.Heroes
{
    public class IndexModel(HeroDbContext context) : PageModel
    {
        public IList<Hero> Hero { get; set; } = default!;
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public string? CurrentCounty { get; set; }
        public string? CurrentState { get; set; }

        public async Task OnGetAsync()
        {
            CurrentCounty = Request.Query["county"].ToString();
            CurrentState = Request.Query["state"].ToString();
            int.TryParse(Request.Query["p"].ToString(), out int pageNumber);
            CurrentPage = pageNumber == 0 ? 1 : pageNumber;


            IQueryable<Hero> heroes = context.Heroes.Where(h => !h.Deleted).OrderBy(h => h.LastName);
            if (!string.IsNullOrWhiteSpace(CurrentCounty))
            {
                if(!string.IsNullOrWhiteSpace(CurrentState))
                    heroes = heroes.Where(h => h.OriginCountyName == CurrentCounty && h.OriginState == CurrentState);
                else
                    heroes = heroes.Where(h => h.OriginCountyName == CurrentCounty);
            }

            TotalPages = (heroes.Count() / 100) + 1;
            heroes = heroes.Skip((CurrentPage - 1) * 100).Take(100);
            if (heroes.Any())
            {
                Hero = await heroes.ToListAsync();
            }
            else
            {
                CurrentPage--;
                if (CurrentPage < 1)
                    CurrentPage = 1;

                Hero = await heroes.Skip((CurrentPage - 1) * 100).Take(100).ToListAsync();
            }
        }

        public FileResult OnGetExport(string state, string county)
        {
            var query = context
                .Heroes
                .Where(h => (!h.Deleted));
            if(!string.IsNullOrWhiteSpace(county))
            {
                query = query.Where(h => h.OriginCountyName == county);
            }
            if (!string.IsNullOrWhiteSpace(state))
            {
                query = query.Where(h => h.OriginState == state);
            }
            var heroes = query.ToList()
                .Select(h => new
                {
                    Id = h.Id,
                    OriginCounty = h.OriginCounty,
                    TreeSite = h.TreeSite,
                    Rank = h.Rank,
                    FirstName = h.FirstName,
                    MiddleName = h.MiddleName,
                    LastName = h.LastName,
                    War = h.War,
                    MilitaryBranch = h.MilitaryBranch,
                    FirstResponderType = h.FirstResponderType,
                    BirthDate = h.BirthDate?.ToString("d"),
                    DateOfDeath = h.DateOfDeath?.ToString("d"),
                    CauseOfDeath = h.CauseOfDeath,
                    LocationOfDeath = h.LocationOfDeath,
                    OriginCity = h.OriginCity,
                    OriginState = h.OriginState,
                    FlagStatus = h.FlagStatus,
                    FlagReceiveStatus = h.FlagReceiveStatus,
                    FlagReceivedDate = h.FlagReceivedDate,
                    FlagSponsor = h.FlagSponsor,
                    OriginLocation = h.OriginLocation,
                    TreeLatitude = h.TreeLatitude,
                    TreeLongitude = h.TreeLongitude,
                    Notes = h.Notes
                }).ToList();
            //Convert heroes to CSV
            //var properties = heroes.GetType().GetGenericArguments().First().GetProperties();
            //var csvString = new StringBuilder();
            //csvString.AppendLine(properties.Select(p => p.Name).Aggregate((p1, p2) => $"{p1},{p2}"));

            using var writer = new StringWriter();
            using var csv = new CsvWriter(writer, CultureInfo.InvariantCulture);
            csv.WriteRecords((IEnumerable)heroes);
            return File(Encoding.UTF8.GetBytes(writer.ToString()), "text/csv", $"{county}.csv");
        }
    }
}

HerosSimpleWebSite/Pages/Heroes/UploadCsv.cshtml.cs
//using Microsoft.AspNetCore.Mvc;
//using Microsoft.AspNetCore.Mvc.RazorPages;
//using Microsoft.EntityFrameworkCore;
//using System.IO.Compression;


//namespace WebSite.Pages.Heroes
//{
//    public class UploadCsvModel : PageModel
//    {
//        public async Task<IActionResult> OnPostUploadAsync()
//        {
//            using (var memoryStream = new MemoryStream())
//            {
//                //await FileUpload.FormFile.CopyToAsync(memoryStream);

//                //// Upload the file if less than 2 MB
//                //if (memoryStream.Length < 2097152)
//                //{
//                //    var file = new AppFile()
//                //    {
//                //        Content = memoryStream.ToArray()
//                //    };

//                //    _dbContext.File.Add(file);

//                //    await _dbContext.SaveChangesAsync();
//                //}
//                //else
//                //{
//                //    ModelState.AddModelError("File", "The file is too large.");
//                //}
//            }

//            return Page();
//        }
//    }
//}

HerosSimpleWebSite/Pages/Heroes/Create.cshtml
@page
@model Heros.Pages.Heroes.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Hero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Hero.War" class="control-label"></label>
                <input asp-for="Hero.War" class="form-control" />
                <span asp-validation-for="Hero.War" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.Specialization" class="control-label"></label>
                <input asp-for="Hero.Specialization" class="form-control" />
                <span asp-validation-for="Hero.Specialization" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.Group" class="control-label"></label>
                <input asp-for="Hero.Group" class="form-control" />
                <span asp-validation-for="Hero.Group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.Name" class="control-label"></label>
                <input asp-for="Hero.Name" class="form-control" />
                <span asp-validation-for="Hero.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.Nickname" class="control-label"></label>
                <input asp-for="Hero.Nickname" class="form-control" />
                <span asp-validation-for="Hero.Nickname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.Prefix" class="control-label"></label>
                <input asp-for="Hero.Prefix" class="form-control" />
                <span asp-validation-for="Hero.Prefix" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.Suffix" class="control-label"></label>
                <input asp-for="Hero.Suffix" class="form-control" />
                <span asp-validation-for="Hero.Suffix" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.HeroType" class="control-label"></label>
                <input asp-for="Hero.HeroType" class="form-control" />
                <span asp-validation-for="Hero.HeroType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.FlagStatus" class="control-label"></label>
                <input asp-for="Hero.FlagStatus" class="form-control" />
                <span asp-validation-for="Hero.FlagStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.FlagReceiveStatus" class="control-label"></label>
                <input asp-for="Hero.FlagReceiveStatus" class="form-control" />
                <span asp-validation-for="Hero.FlagReceiveStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.FlagReceivedDate" class="control-label"></label>
                <input asp-for="Hero.FlagReceivedDate" class="form-control" />
                <span asp-validation-for="Hero.FlagReceivedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.FlagSponsor" class="control-label"></label>
                <input asp-for="Hero.FlagSponsor" class="form-control" />
                <span asp-validation-for="Hero.FlagSponsor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.MilitaryBranch" class="control-label"></label>
                <input asp-for="Hero.MilitaryBranch" class="form-control" />
                <span asp-validation-for="Hero.MilitaryBranch" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.BirthMonth" class="control-label"></label>
                <input asp-for="Hero.BirthMonth" class="form-control" />
                <span asp-validation-for="Hero.BirthMonth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.BirthDay" class="control-label"></label>
                <input asp-for="Hero.BirthDay" class="form-control" />
                <span asp-validation-for="Hero.BirthDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.BirthYear" class="control-label"></label>
                <input asp-for="Hero.BirthYear" class="form-control" />
                <span asp-validation-for="Hero.BirthYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.FirstName" class="control-label"></label>
                <input asp-for="Hero.FirstName" class="form-control" />
                <span asp-validation-for="Hero.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.MiddleName" class="control-label"></label>
                <input asp-for="Hero.MiddleName" class="form-control" />
                <span asp-validation-for="Hero.MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.LastName" class="control-label"></label>
                <input asp-for="Hero.LastName" class="form-control" />
                <span asp-validation-for="Hero.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.Rank" class="control-label"></label>
                <input asp-for="Hero.Rank" class="form-control" />
                <span asp-validation-for="Hero.Rank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.DateOfDeath" class="control-label"></label>
                <input asp-for="Hero.DateOfDeath" class="form-control" />
                <span asp-validation-for="Hero.DateOfDeath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.TreeStatus" class="control-label"></label>
                <input asp-for="Hero.TreeStatus" class="form-control" />
                <span asp-validation-for="Hero.TreeStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.TreeLatitude" class="control-label"></label>
                <input asp-for="Hero.TreeLatitude" class="form-control" />
                <span asp-validation-for="Hero.TreeLatitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.TreeLongitude" class="control-label"></label>
                <input asp-for="Hero.TreeLongitude" class="form-control" />
                <span asp-validation-for="Hero.TreeLongitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.CauseOfDeath" class="control-label"></label>
                <input asp-for="Hero.CauseOfDeath" class="form-control" />
                <span asp-validation-for="Hero.CauseOfDeath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.LocationOfDeath" class="control-label"></label>
                <input asp-for="Hero.LocationOfDeath" class="form-control" />
                <span asp-validation-for="Hero.LocationOfDeath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.OriginCity" class="control-label"></label>
                <input asp-for="Hero.OriginCity" class="form-control" />
                <span asp-validation-for="Hero.OriginCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.OriginCounty" class="control-label"></label>
                <input asp-for="Hero.OriginCounty" class="form-control" />
                <span asp-validation-for="Hero.OriginCounty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.OriginState" class="control-label"></label>
                <input asp-for="Hero.OriginState" class="form-control" />
                <span asp-validation-for="Hero.OriginState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.OriginLocation" class="control-label"></label>
                <input asp-for="Hero.OriginLocation" class="form-control" />
                <span asp-validation-for="Hero.OriginLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.OriginRegionCode" class="control-label"></label>
                <input asp-for="Hero.OriginRegionCode" class="form-control" />
                <span asp-validation-for="Hero.OriginRegionCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.OriginRegionName" class="control-label"></label>
                <input asp-for="Hero.OriginRegionName" class="form-control" />
                <span asp-validation-for="Hero.OriginRegionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.OriginDivisionCode" class="control-label"></label>
                <input asp-for="Hero.OriginDivisionCode" class="form-control" />
                <span asp-validation-for="Hero.OriginDivisionCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.OriginDivisionName" class="control-label"></label>
                <input asp-for="Hero.OriginDivisionName" class="form-control" />
                <span asp-validation-for="Hero.OriginDivisionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.OriginStateFipsCode" class="control-label"></label>
                <input asp-for="Hero.OriginStateFipsCode" class="form-control" />
                <span asp-validation-for="Hero.OriginStateFipsCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.OriginStateName" class="control-label"></label>
                <input asp-for="Hero.OriginStateName" class="form-control" />
                <span asp-validation-for="Hero.OriginStateName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.CountyCodeFips" class="control-label"></label>
                <input asp-for="Hero.CountyCodeFips" class="form-control" />
                <span asp-validation-for="Hero.CountyCodeFips" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hero.OriginCountyName" class="control-label"></label>
                <input asp-for="Hero.OriginCountyName" class="form-control" />
                <span asp-validation-for="Hero.OriginCountyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HerosSimpleWebSite/Pages/Heroes/Index.cshtml
@page
@model Heros.Pages.Heroes.IndexModel

@{
    ViewData["Title"] = "Nebraska Heroes";
}

<h1>Nebraska Heroes</h1>

@* <p>
    <a asp-page="Create">Create New</a>
</p> *@
<a asp-route-county="@Model.CurrentCounty" asp-route-p="@(Model.CurrentPage - 1)">Prev Page</a>
| Page @(Model.CurrentPage) of @Model.TotalPages |
<a asp-route-county="@Model.CurrentCounty" asp-route-p="@(Model.CurrentPage + 1)">Next Page</a>
|
<a asp-route-county="@Model.CurrentCounty" asp-route-county="@Model.CurrentState" asp-page-handler="Export">Export</a>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].OriginCounty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].OriginState)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].TreeSite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].Rank)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].MiddleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].War)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].MilitaryBranch)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].FirstResponderType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].BirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].DateOfDeath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].CauseOfDeath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].LocationOfDeath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].OriginCity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].FlagStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].FlagReceiveStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].FlagReceivedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].FlagSponsor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].TreeLatitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].TreeLongitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hero[0].Notes)
            </th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Hero)
    {
        <tr>
            <td>
                @*                     <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a> *@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OriginCounty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OriginState)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TreeSite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.War)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MilitaryBranch)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstResponderType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfDeath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CauseOfDeath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationOfDeath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OriginCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlagStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlagReceiveStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlagReceivedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlagSponsor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TreeLatitude)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TreeLongitude)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>

        </tr>
    }
    </tbody>
</table>
<a asp-route-county="@Model.CurrentCounty" asp-route-p="@(Model.CurrentPage - 1)">Prev Page</a>
| Page @(Model.CurrentPage) of @Model.TotalPages |
<a asp-route-county="@Model.CurrentCounty" asp-route-p="@(Model.CurrentPage + 1)">Next Page</a>
|
<a asp-route-county="@Model.CurrentCounty" asp-route-county="@Model.CurrentState" asp-page-handler="Export">Export</a>

HerosSimpleWebSite/Pages/Heroes/UploadCsv.cshtml
@* @page
@model WebSite.Pages.Heroes.UploadCsvModel
@{
}

<form enctype="multipart/form-data" method="post">
    <dl>
        <dt>
            <label asp-for="FileUpload.FormFile"></label>
        </dt>
        <dd>
            <input asp-for="FileUpload.FormFile" type="file">
        </dd>
    </dl>
    <input asp-page-handler="Upload" class="btn" type="submit" value="Upload">
</form> *@